language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key: "2d789620-e3f1-4d81-a4ea-f79cc5d54c76"
  app: json-to-excel-server
  skip_cleanup: true
install:
  - npm install
script:
  - npm test
services:
  - mongodb